# Generated by Django 4.2.16 on 2024-10-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id_topic', models.IntegerField(primary_key=True, serialize=False)),
                ('name_topic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcards',
            fields=[
                ('id_flashcard', models.IntegerField(primary_key=True, serialize=False)),
                ('front', models.CharField(max_length=200)),
                ('back', models.CharField(max_length=300)),
                ('id_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.topic')),
            ],
        ),
    ]
