# Generated by Django 4.2.16 on 2024-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcards_id_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='slug_flashcard',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='flashcards',
            name='slug_topic',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug_topic',
            field=models.SlugField(default=''),
        ),
    ]
