# Generated by Django 4.2.16 on 2024-10-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcards_id_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image_topic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
