# Generated by Django 4.2.16 on 2024-10-24 08:22

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcards_slug_flashcards_topic_slug_topic'),
    ]

    operations = [
        migrations.RunSQL(
            """
            PRAGMA foreign_keys=off;
            CREATE TABLE flashcards_flashcards_new AS SELECT * FROM flashcards_flashcards;
            ALTER TABLE flashcards_flashcards RENAME TO flashcards_flashcards_old;
            ALTER TABLE flashcards_flashcards_new RENAME TO flashcards_flashcards;
            DROP TABLE flashcards_flashcards_old;
            PRAGMA foreign_keys=on;
            """,
            reverse_sql="""
            PRAGMA foreign_keys=off;
            CREATE TABLE flashcards_flashcards_old AS SELECT * FROM flashcards_flashcards;
            ALTER TABLE flashcards_flashcards RENAME TO flashcards_flashcards_new;
            ALTER TABLE flashcards_flashcards_old RENAME TO flashcards_flashcards;
            DROP TABLE flashcards_flashcards_new;
            PRAGMA foreign_keys=on;
            """
        ),
    ]

