# Generated by Django 4.2.16 on 2024-10-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcards_slug_flashcard_flashcards_slug_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='type_topic',
            field=models.CharField(default='', max_length=50),
        ),
    ]
