# Generated by Django 4.2.16 on 2024-10-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcards_slug_flashcards_topic_slug_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcards',
            old_name='slug_flashcards',
            new_name='slug_flashcard',
        ),
    ]
