# Generated by Django 4.2.16 on 2024-10-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_topic_type_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcards',
            name='slug_topic',
        ),
    ]
