# Generated by Django 4.2.16 on 2024-11-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_topic_image_topic'),
        ('flashcards', '0005_rename_slug_flashcards_flashcards_slug_flashcard'),
    ]

    operations = [
    ]
