# Generated by Django 4.2.16 on 2024-11-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_rename_slug_flashcards_flashcards_slug_flashcard'),
        ('flashcards', '0006_remove_flashcards_slug_topic'),
    ]

    operations = [
    ]
