# Generated by Django 4.2.16 on 2024-11-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_merge_20241108_2157'),
        ('flashcards', '0008_user_study'),
    ]

    operations = [
    ]
