# Generated by Django 4.2.16 on 2024-11-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_user_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='pronunciation',
            field=models.URLField(default=''),
        ),
    ]
