# Generated by Django 4.2.16 on 2024-11-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_merge_0006_merge_20241108_2157_0008_user_study'),
        ('flashcards', '0010_alter_flashcards_pronunciation_and_more'),
    ]

    operations = [
    ]
