# Generated by Django 4.2.16 on 2024-11-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_merge_20241113_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcards',
            name='pronunciation',
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='slug_flashcard',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='slug_study',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug_topic',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='type_topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug_user',
            field=models.SlugField(blank=True),
        ),
    ]
