# Generated by Django 4.2.16 on 2024-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_remove_flashcards_pronunciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='pronunciation',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='slug_flashcard',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
