# Generated by Django 4.2.16 on 2024-11-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_alter_flashcards_slug_flashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='pronunciation',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='slug_flashcard',
            field=models.SlugField(blank=True),
        ),
    ]
