# Generated by Django 4.2.16 on 2024-11-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_alter_flashcards_pronunciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='spell',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
