# Generated by Django 4.2.16 on 2024-11-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_flashcards_spell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcards',
            name='slug_flashcards',
        ),
    ]
