# Generated by Django 4.2.16 on 2024-11-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0019_topic_created_by_topic_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='spell',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
