# Generated by Django 4.2.16 on 2024-11-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0020_alter_flashcards_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_default',
            field=models.BooleanField(null=True),
        ),
    ]
