<<<<<<< HEAD
# Generated by Django 4.2.16 on 2024-11-20 14:26
=======
# Generated by Django 4.2.16 on 2024-11-20 15:35
>>>>>>> 2f1edc40b0377e3dbb844fec3ce304fe0e6aa9fa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0020_alter_flashcards_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_default',
<<<<<<< HEAD
            field=models.BooleanField(default=True),
=======
            field=models.BooleanField(null=True),
>>>>>>> 2f1edc40b0377e3dbb844fec3ce304fe0e6aa9fa
        ),
    ]
