<<<<<<< HEAD
# Generated by Django 4.2.16 on 2024-11-20 15:24
=======
# Generated by Django 4.2.16 on 2024-11-20 15:37
>>>>>>> 2f1edc40b0377e3dbb844fec3ce304fe0e6aa9fa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0021_alter_topic_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
