# Generated by Django 4.2.16 on 2024-11-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0022_alter_topic_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_default',
            field=models.BooleanField(null=True),
        ),
    ]
